### ISSUE TITLE
Be robust to different platforms' psutil function availability

### ISSUE THREAD

**Issue by ericaltendorf** [ericaltendorf/plotman#38]
psutil offers some functions which are platform dependent.  we could be more robust and simply not report ones that aren't available.

e.g., fix this stacktrace:
```File "/home/chia/plotman-main/interactive.py", line 207, in curses_main
    jobs_win.addstr(0, 0, reporting.status_report(jobs, n_cols, jobs_height, 
  File "/home/chia/plotman-main/reporting.py", line 107, in status_report
    plot_util.time_format(j.get_time_iowait())
  File "/home/chia/plotman-main/job.py", line 282, in get_time_iowait
    return int(self.proc.cpu_times().iowait)
AttributeError: 'pcputimes' object has no attribute 'iowait'```

Should check the other calls to psutil as well.

**Comment by ctrlaltdel** [comment]
Hi @ericaltendorf,

Thanks for this useful tool!

For the record, everything else works fine on Ubuntu 20.04 using package python3-psutis version 5.5.1-1ubuntu4 and the following hack.

```diff
     def get_time_iowait(self):
-        return int(self.proc.cpu_times().iowait)
+        return 0
```

Happy to make a proper PR for this if useful.

**Comment by toastygunn** [comment]
My neighbor who I got into chia recently found the root cause of this issue. You need psutil ver 5.8 or better.
On his plotter which generated this error message, and my newly rebuild farmer which I decided could also do a little bit o' plotting before mainnet, you need psutil ver 5.6 or better (we installed 5.8).

$pip3 freeze
On problematic systems, this reports psutil==5.5.1

To install the newer ver, you need to type:
$pip3 install psutil==5.8

I dunno where the old ver came from, maybe apt get python-psutil? 
It doesn't matter b/c the problem is solved now for us by upgrading psutil without having to hack the job.py with a fake integer.
